/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'GhinY' at '11/04/16 21:25' with Gradle 2.12
 *
 * @author GhinY, @date 11/04/16 21:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
