/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'GhinY' at '12/04/16 10:55' with Gradle 2.12
 *
 * @author GhinY, @date 12/04/16 10:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
